import React, { useState } from 'react'
import './Otp_responsiveness.css'
import logo from '../images/logo.png'
import Card from "react-bootstrap/Card";
import Form from 'react-bootstrap/esm/Form';
import { useNavigate } from 'react-router-dom';
import { deleteUser } from 'firebase/auth';
import { auth } from '../Firebase/Firebase';
import {clickFunctionSignup} from './Signup.jsx'


export default function OTP() {

    const navigate = useNavigate();

    const [formData, setFormData] = useState({
        otp: "",
    })


    const handleinput = (e) => {
        const name = e.target.name;
        const otp = e.target.value;

        setFormData({ ...formData, [name]: otp })

        if (otp.length === 6) {
            let confirmationResult = window.confirmationResult;
            confirmationResult.confirm(otp).then((result) => {
                // User signed in successfully.

                //Deleting a user process started - Extra User Generated by phone number login
                const user = auth.currentUser;
                deleteUser(user).then(() => {
                    // User deleted.
                    console.log("User Deleted");
                }).catch((error) => {
                    // An error ocurred
                    const errorCode = error.code;
                    const errorMessage = error.message;
                    console.log(errorCode, errorMessage);
                });
                //Deleting user code complete   


                // console.log(localStorage);
                clickFunctionSignup(localStorage.getItem('email'), localStorage.getItem('password')); //Creating User with email and password signup. Email and password are collected from signup form and stored in local storage.
                localStorage.removeItem('password'); //Deleting from local storage once password is used
                navigate("/Userdashboard", { replace: true }) //Navigate to home once signup is complete

                // ...
            }).catch((error) => {
                // User couldn't sign in (bad verification code?) Wrong OTP entered
                const errorCode = error.code;
                const errorMessage = error.message;
                console.log(errorCode, errorMessage);
                alert("Wrong OTP Entered")
                navigate("/signup") // Navigate to signup if OTP entered is wrong
            });
        }
    }


    return (
        <>
            <div className="otp_main" style={{
                        width: '100%',
                        minHeight: '100vh',
                        background: 'linear-gradient(to top,white 0%,white 50%,#0089ED 50%,#0089ED 100%)',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                }}>

                    <div className="showcase-top">
                        <img src={logo} alt="MIT Logo" style={{
                            width: '75px',
                            height: '75px',
                            margin: '-700% 0% 0% -500%',
                            backgroundColor: 'white',
                            borderRadius: '5%',
                        }} />
                    </div>

                    <div className="signinCard1" style={{
                        zIndex: '1',
                        boxShadow: '23px 18px 64px -19px rgba(0, 0, 0, 0.75)',
                    }} >

                        <Card style={{ width: '100%' }}>
                            <Card.Body>
                                <Card.Title className="card"><span className='title'>OTP Verification</span></Card.Title>


                                <Form style={{
                                    marginTop: '5%',
                                    // marginLeft: '2%',
                                }}>
                                    <Form.Group className="mb-3" controlId="formBasicEmail" style={{
                                        marginLeft: '10%',
                                        width: '80%',
                                        padding: '3% 3% 3% 3%',
                                        backgroundColor: '#D4ECDE',
                                        borderRadius: '2%',
                                    }}>
                                        <Form.Label className="otp_label">We have Sent a Verification Code to Your Phone Number</Form.Label>
                                    </Form.Group>

                                    <Form.Group className="mb-3" controlId="formBasicPassword"
                                        style={{
                                            width:'80%',
                                            padding: '1% 0% 8% 6%',
                                        }}>
                                        <input className='otp_input' type="password" placeholder="Enter Verification Code"
                                            name="otp" id="otp"
                                            onChange={handleinput} value={formData.otp}
                                            style={{
                                                width:'80%',
                                                paddingTop: '3%',
                                                paddingBottom: '3%',
                                                paddingLeft: "4%",
                                                marginTop: '1%',
                                                borderRadius: '2%',
                                                borderColor: '#4285F4',

                                            }} />
                                    </Form.Group>

                                </Form>

                            </Card.Body>
                        </Card>
                    </div>
            </div>
        </>
    )
}
